import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { existsSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Detect entry point: prefer src/main.ts, fallback to main.ts
const hasSrcMain = existsSync("src/main.ts");
const hasRootMain = existsSync("main.ts");

if (hasSrcMain && hasRootMain) {
  console.warn("WARNING: Both src/main.ts and main.ts exist. Using src/main.ts as entry point.");
  console.warn("Consider removing one to avoid confusion.");
}

const entryPoint = hasSrcMain ? "src/main.ts" : "main.ts";

if (!hasSrcMain && !hasRootMain) {
  console.error("ERROR: Neither src/main.ts nor main.ts found!");
  process.exit(1);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
